include(
    ":common:composeui:components",
    ":common:composeui:pages:simple",
    ":common:data:appeal:model",
    ":common:data:preset:model",
    ":common:data:preset:infra",
    ":common:data:producer:model",
    ":common:database",
    ":common:utilities",
    ":android",
    ":desktop",
    ":web",
)
