package net.subroh0508.wingcalculator.composeui.pages.simple

internal enum class Strings {
    CommentFormLabel,
    CommentFormPlaceholder,
    WeekSelectorLabel,
    WeekSelectorUnit,
    AppealRatioSelectorLabel,
    AppealRatioSelectorUnit,
    AppealJudgeSelectorLabel,
    MemoryLevelSelectorLabel,
    VocalBuffRatioLabel,
    DanceBuffRatioLabel,
    VisualBuffRatioLabel,
    BuffRatioHelperText,
    InterestRatioLabel,
    InterestRatioHelperText,
    ProduceIdolStatusFormLabel,
    SupportIdolStatusFormLabel,
    IdolVocalStatusFormLabel,
    IdolDanceStatusFormLabel,
    IdolVisualStatusFormLabel,
    IdolMentalStatusFormLabel,
    BackdropFrontLayerHeaderTitle,
    TableSwitcherAppealLabel,
    TableSwitcherAppealLabelVocal,
    TableSwitcherAppealLabelDance,
    TableSwitcherAppealLabelVisual,
    TableSwitcherAppealLabelMemory,
    TableSwitcherJudgeLabel,
    TableSwitcherJudgeLabelVocal,
    TableSwitcherJudgeLabelDance,
    TableSwitcherJudgeLabelVisual,
    TableColumnLabelProduce,
    TableColumnLabelSupport1,
    TableColumnLabelSupport2,
    TableColumnLabelSupport3,
    TableColumnLabelSupport4,
    PresetSaveDialogTitle,
    PresetSaveMenuCreate,
    PresetSaveMenuUpdate,
    PresetSearchBarText,
    PresetSearchBarPlaceholder,
    MessageSearchPresetSuggestsEmpty,
}

internal expect fun getString(string: Strings, vararg arg: Any): String
