package net.subroh0508.wingcalculator.composeui.pages.simple

import androidx.compose.runtime.Composable

@Composable
internal actual fun getString(string: Strings, vararg arg: Any) = when (string) {
    Strings.CommentFormLabel -> "メモ"
    Strings.CommentFormPlaceholder -> "メモを入力"
    Strings.WeekSelectorLabel -> "シーズン・週"
    Strings.WeekSelectorUnit -> "${arg[0]}週目"
    Strings.AppealRatioSelectorLabel -> "アピール倍率"
    Strings.AppealRatioSelectorUnit -> "${arg[0]}倍"
    Strings.AppealJudgeSelectorLabel -> "アピール判定"
    Strings.MemoryLevelSelectorLabel -> "思い出Lv"
    Strings.VocalBuffRatioLabel -> "Voバフ補正: ${arg[0]}"
    Strings.DanceBuffRatioLabel -> "Daバフ補正: ${arg[0]}"
    Strings.VisualBuffRatioLabel -> "Viバフ補正: ${arg[0]}"
    Strings.BuffRatioHelperText -> "カンマ区切り(単位: %)"
    Strings.InterestRatioLabel -> "興味度: ${arg[0]}"
    Strings.InterestRatioHelperText -> "カンマ区切り"
    Strings.ProduceIdolStatusFormLabel -> "プロデュースアイドル"
    Strings.SupportIdolStatusFormLabel -> "サポートアイドル(${arg[0]})"
    Strings.IdolVocalStatusFormLabel -> "Vo"
    Strings.IdolDanceStatusFormLabel -> "Da"
    Strings.IdolVisualStatusFormLabel -> "Vi"
    Strings.IdolMentalStatusFormLabel -> "Me"
    Strings.BackdropFrontLayerHeaderTitle -> "計算結果"
    Strings.TableSwitcherAppealLabel -> "アピール種別"
    Strings.TableSwitcherAppealLabelVocal -> "Voアピール"
    Strings.TableSwitcherAppealLabelDance -> "Daアピール"
    Strings.TableSwitcherAppealLabelVisual -> "Viアピール"
    Strings.TableSwitcherAppealLabelMemory -> "思い出"
    Strings.TableSwitcherJudgeLabel -> "審査員"
    Strings.TableSwitcherJudgeLabelVocal -> "Vo審査員"
    Strings.TableSwitcherJudgeLabelDance -> "Da審査員"
    Strings.TableSwitcherJudgeLabelVisual -> "Vi審査員"
    Strings.TableColumnLabelProduce -> "P"
    Strings.TableColumnLabelSupport1 -> "S1"
    Strings.TableColumnLabelSupport2 -> "S2"
    Strings.TableColumnLabelSupport3 -> "S3"
    Strings.TableColumnLabelSupport4 -> "S4"
    Strings.PresetSaveDialogTitle -> "プリセット名を入力"
    Strings.PresetSaveMenuCreate -> "新規プリセット"
    Strings.PresetSaveMenuUpdate -> "プリセット名変更"
    Strings.PresetSearchBarText -> "プリセット名: ${arg[0]}"
    Strings.PresetSearchBarPlaceholder -> "プリセットを検索"
    Strings.MessageSearchPresetSuggestsEmpty -> "条件に一致するプリセットが見つかりません"
}